-- Fund Estimator security hardening
-- Apply through the Supabase migration workflow after taking a backup and
-- running the preflight queries documented in docs/SECURITY_DEPLOYMENT.md.
-- This file is intentionally never executed by the application.

begin;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create table if not exists public.app_users (
    user_id text primary key,
    phone text not null unique,
    password_hash text not null,
    auth_user_id uuid,
    developer text,
    inviter text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.app_users add column if not exists auth_user_id uuid;

create table if not exists public.app_watchlist (
    id bigint generated by default as identity primary key,
    user_id text not null,
    code text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.app_adjustments (
    id text not null,
    user_id text not null,
    type text not null,
    code text not null,
    effective_date date not null,
    shares double precision not null default 0,
    price double precision not null default 0,
    cash double precision not null default 0,
    note text,
    source text not null default 'manual',
    created_at timestamptz not null default now()
);

alter table public.app_adjustments
    add column if not exists source text;

update public.app_adjustments
set source = case
    when lower(coalesce(note, '')) like '%[ui_edit]%'
      or lower(coalesce(note, '')) like 'edit->%'
      or lower(coalesce(note, '')) like 'ui_edit%'
      or lower(coalesce(note, '')) like 'ui edit%'
      or coalesce(note, '') like 'UI编辑%'
    then 'ui_edit'
    else 'manual'
end
where source is null or btrim(source) = '';

alter table public.app_adjustments
    alter column source set default 'manual',
    alter column source set not null;

create table if not exists public.app_daily_ledger (
    user_id text not null,
    date date not null,
    code text not null,
    shares_end double precision not null default 0,
    avg_cost_nav_end double precision not null default 0,
    realized_pnl_end double precision not null default 0,
    estimated_nav_close double precision,
    estimated_pnl_close double precision,
    official_nav double precision,
    official_pnl double precision,
    settle_status text not null default 'estimated_only',
    updated_at timestamptz not null default now()
);

-- Fail closed instead of silently deleting or merging potentially conflicting
-- user data. Resolve any reported duplicates using the documented preflight.
do $$
begin
    if exists (
        select 1 from public.app_users
        where user_id is null or btrim(user_id::text) = ''
           or phone is null or btrim(phone::text) = ''
           or password_hash is null or btrim(password_hash::text) = ''
    ) then
        raise exception using
            errcode = '23502',
            message = 'security migration blocked: incomplete app_users identity rows';
    end if;
    if exists (
        select 1 from public.app_watchlist
        where user_id is null or btrim(user_id::text) = ''
           or code is null or btrim(code::text) = ''
    ) or exists (
        select 1 from public.app_adjustments
        where user_id is null or btrim(user_id::text) = ''
           or id is null or btrim(id::text) = ''
           or code is null or btrim(code::text) = ''
    ) or exists (
        select 1 from public.app_daily_ledger
        where user_id is null or btrim(user_id::text) = ''
           or code is null or btrim(code::text) = ''
    ) then
        raise exception using
            errcode = '23502',
            message = 'security migration blocked: business rows without an owner/key';
    end if;
    if exists (
        select 1 from public.app_users
        group by phone
        having count(*) > 1
    ) then
        raise exception using
            errcode = '23505',
            message = 'security migration blocked: duplicate app_users.phone values';
    end if;
    if exists (
        select 1 from public.app_users
        group by user_id
        having count(*) > 1
    ) then
        raise exception using
            errcode = '23505',
            message = 'security migration blocked: duplicate app_users.user_id values';
    end if;
    if exists (
        select 1 from public.app_watchlist
        group by user_id, code
        having count(*) > 1
    ) then
        raise exception using
            errcode = '23505',
            message = 'security migration blocked: duplicate app_watchlist owner/code values';
    end if;
    if exists (
        select 1 from public.app_adjustments
        group by user_id, id
        having count(*) > 1
    ) then
        raise exception using
            errcode = '23505',
            message = 'security migration blocked: duplicate app_adjustments owner/id values';
    end if;
    if exists (
        select 1 from public.app_daily_ledger
        group by user_id, date, code
        having count(*) > 1
    ) then
        raise exception using
            errcode = '23505',
            message = 'security migration blocked: duplicate app_daily_ledger owner/date/code values';
    end if;
end
$$;

alter table public.app_users
    alter column user_id set not null,
    alter column phone set not null,
    alter column password_hash set not null;
alter table public.app_watchlist
    alter column user_id set not null,
    alter column code set not null;
alter table public.app_adjustments
    alter column user_id set not null,
    alter column id set not null,
    alter column code set not null;
alter table public.app_daily_ledger
    alter column user_id set not null,
    alter column code set not null;

create unique index if not exists app_users_phone_uidx
    on public.app_users (phone);
create unique index if not exists app_users_user_id_uidx
    on public.app_users (user_id);
create unique index if not exists app_users_auth_user_id_uidx
    on public.app_users (auth_user_id)
    where auth_user_id is not null;

create unique index if not exists app_watchlist_user_code_uidx
    on public.app_watchlist (user_id, code);
create index if not exists app_watchlist_user_id_idx
    on public.app_watchlist (user_id);

create unique index if not exists app_adjustments_user_id_id_uidx
    on public.app_adjustments (user_id, id);
create index if not exists app_adjustments_user_date_code_idx
    on public.app_adjustments (user_id, effective_date, code, created_at, id);

create unique index if not exists app_daily_ledger_user_date_code_uidx
    on public.app_daily_ledger (user_id, date, code);
create index if not exists app_daily_ledger_user_code_date_idx
    on public.app_daily_ledger (user_id, code, date desc);

create or replace function private.current_app_user_id()
returns text
language sql
stable
security definer
set search_path = pg_catalog
as $$
    select u.user_id
    from public.app_users as u
    where u.auth_user_id = (select auth.uid())
    limit 1
$$;

revoke all on function private.current_app_user_id() from public;
grant execute on function private.current_app_user_id() to authenticated, service_role;

alter table public.app_users enable row level security;
alter table public.app_watchlist enable row level security;
alter table public.app_adjustments enable row level security;
alter table public.app_daily_ledger enable row level security;

drop policy if exists app_users_select_self on public.app_users;
create policy app_users_select_self
on public.app_users
for select
to authenticated
using (auth_user_id = (select auth.uid()));

drop policy if exists app_watchlist_owner_all on public.app_watchlist;
create policy app_watchlist_owner_all
on public.app_watchlist
for all
to authenticated
using (user_id = (select private.current_app_user_id()))
with check (user_id = (select private.current_app_user_id()));

drop policy if exists app_adjustments_owner_all on public.app_adjustments;
create policy app_adjustments_owner_all
on public.app_adjustments
for all
to authenticated
using (user_id = (select private.current_app_user_id()))
with check (user_id = (select private.current_app_user_id()));

drop policy if exists app_daily_ledger_owner_all on public.app_daily_ledger;
create policy app_daily_ledger_owner_all
on public.app_daily_ledger
for all
to authenticated
using (user_id = (select private.current_app_user_id()))
with check (user_id = (select private.current_app_user_id()));

revoke all on public.app_users from anon, authenticated;
grant select (user_id, phone, auth_user_id, developer, inviter, created_at, updated_at)
    on public.app_users to authenticated;

revoke all on public.app_watchlist from anon;
revoke all on public.app_adjustments from anon;
revoke all on public.app_daily_ledger from anon;
grant select, insert, update, delete on public.app_watchlist to authenticated;
grant select, insert, update, delete on public.app_adjustments to authenticated;
grant select, insert, update, delete on public.app_daily_ledger to authenticated;

do $$
declare
    v_watchlist_sequence text;
begin
    v_watchlist_sequence := pg_get_serial_sequence('public.app_watchlist', 'id');
    if v_watchlist_sequence is not null then
        execute format(
            'grant usage, select on sequence %s to authenticated',
            v_watchlist_sequence
        );
    end if;
end
$$;

-- Atomically replaces only the selected day's UI-generated adjustment rows,
-- replays the remaining position, and writes the minimal rows needed to reach
-- the requested end-of-day target. PostgreSQL executes one RPC call in one
-- transaction; any exception rolls the entire edit back.
create or replace function public.app_apply_position_edit(
    p_user_id text,
    p_effective_date date,
    p_code text,
    p_shares_end double precision,
    p_avg_cost_nav_end double precision,
    p_realized_pnl_end double precision default 0,
    p_note text default null
)
returns jsonb
language plpgsql
security invoker
set search_path = pg_catalog
as $$
declare
    v_row record;
    v_shares double precision := 0;
    v_avg double precision := 0;
    v_realized double precision := 0;
    v_delta double precision := 0;
    v_trade_shares double precision := 0;
    v_trade_price double precision := 0;
    v_old_amount double precision := 0;
    v_rebalance_shares double precision := 0;
    v_deleted integer := 0;
    v_inserted integer := 0;
    v_note text := nullif(btrim(p_note), '');
    v_created_at timestamptz := clock_timestamp();
begin
    if p_user_id is null or btrim(p_user_id) = '' or length(p_user_id) > 128 then
        raise exception using errcode = '22023', message = 'invalid user identifier';
    end if;
    if p_code is null or p_code !~ '^[0-9]{6}$' then
        raise exception using errcode = '22023', message = 'invalid fund code';
    end if;
    if p_effective_date is null then
        raise exception using errcode = '22023', message = 'invalid effective date';
    end if;
    if p_shares_end::text in ('NaN', 'Infinity', '-Infinity')
       or p_avg_cost_nav_end::text in ('NaN', 'Infinity', '-Infinity')
       or p_realized_pnl_end::text in ('NaN', 'Infinity', '-Infinity')
       or p_shares_end < 0
       or p_shares_end > 1e15
       or p_avg_cost_nav_end < 0
       or p_avg_cost_nav_end > 1e12
       or abs(p_realized_pnl_end) > 1e18
       or (p_shares_end > 0 and p_avg_cost_nav_end <= 0) then
        raise exception using errcode = '22023', message = 'invalid position target';
    end if;
    if v_note is not null and length(v_note) > 500 then
        raise exception using errcode = '22023', message = 'position note is too long';
    end if;

    -- Authenticated callers may only address their mapped application user.
    -- SQL editor/admin and service_role calls have no auth.uid() and are
    -- additionally protected by function/table grants.
    if (select auth.uid()) is not null
       and p_user_id is distinct from (select private.current_app_user_id()) then
        raise exception using errcode = '42501', message = 'position owner mismatch';
    end if;

    perform pg_advisory_xact_lock(
        hashtextextended(p_user_id || ':' || p_effective_date::text || ':' || p_code, 0)
    );

    delete from public.app_adjustments
    where user_id = p_user_id
      and code = p_code
      and effective_date = p_effective_date
      and (
          lower(coalesce(source, '')) = 'ui_edit'
          or (
              coalesce(source, '') = ''
              and (
                  lower(coalesce(note, '')) like '%[ui_edit]%'
                  or lower(coalesce(note, '')) like 'edit->%'
                  or lower(coalesce(note, '')) like 'ui_edit%'
                  or lower(coalesce(note, '')) like 'ui edit%'
                  or coalesce(note, '') like 'UI编辑%'
              )
          )
      );
    get diagnostics v_deleted = row_count;

    for v_row in
        select type, shares, price, cash
        from public.app_adjustments
        where user_id = p_user_id
          and code = p_code
          and effective_date <= p_effective_date
        order by effective_date asc, created_at asc nulls last, id asc
    loop
        if upper(coalesce(v_row.type, '')) = 'BUY'
           and coalesce(v_row.shares, 0) > 0
           and coalesce(v_row.price, 0) > 0 then
            v_old_amount := v_shares * v_avg;
            v_shares := v_shares + v_row.shares;
            v_avg := (v_old_amount + v_row.shares * v_row.price) / v_shares;
        elsif upper(coalesce(v_row.type, '')) = 'SELL'
              and coalesce(v_row.shares, 0) > 0
              and coalesce(v_row.price, 0) > 0 then
            v_trade_shares := least(v_row.shares, greatest(v_shares, 0));
            v_realized := v_realized + (v_row.price - v_avg) * v_trade_shares;
            v_shares := v_shares - v_trade_shares;
            if v_shares <= 1e-9 then
                v_shares := 0;
                v_avg := 0;
            end if;
        elsif upper(coalesce(v_row.type, '')) = 'CASH_ADJ' then
            v_realized := v_realized + coalesce(v_row.cash, 0);
        end if;
    end loop;

    v_delta := p_shares_end - v_shares;
    if abs(v_delta) > 1e-9 then
        v_trade_price := case
            when p_avg_cost_nav_end > 0 then p_avg_cost_nav_end
            else 1
        end;
        if v_delta > 0 then
            v_created_at := v_created_at + interval '1 microsecond';
            insert into public.app_adjustments (
                id, user_id, type, code, effective_date, shares, price,
                cash, note, source, created_at
            ) values (
                replace(gen_random_uuid()::text, '-', ''), p_user_id, 'BUY',
                p_code, p_effective_date, v_delta, v_trade_price, 0,
                coalesce(v_note, 'edit->BUY'), 'ui_edit', v_created_at
            );
            v_old_amount := v_shares * v_avg;
            v_shares := v_shares + v_delta;
            v_avg := (v_old_amount + v_delta * v_trade_price) / v_shares;
        else
            v_trade_shares := least(abs(v_delta), greatest(v_shares, 0));
            v_created_at := v_created_at + interval '1 microsecond';
            insert into public.app_adjustments (
                id, user_id, type, code, effective_date, shares, price,
                cash, note, source, created_at
            ) values (
                replace(gen_random_uuid()::text, '-', ''), p_user_id, 'SELL',
                p_code, p_effective_date, v_trade_shares, v_trade_price, 0,
                coalesce(v_note, 'edit->SELL'), 'ui_edit', v_created_at
            );
            v_realized := v_realized + (v_trade_price - v_avg) * v_trade_shares;
            v_shares := v_shares - v_trade_shares;
            if v_shares <= 1e-9 then
                v_shares := 0;
                v_avg := 0;
            end if;
        end if;
        v_inserted := v_inserted + 1;
    end if;

    if v_shares > 0 and abs(v_avg - p_avg_cost_nav_end) > 1e-9 then
        if p_avg_cost_nav_end > v_avg then
            v_rebalance_shares := v_shares;
            v_trade_price := greatest(0.000001, 2 * p_avg_cost_nav_end - v_avg);
        else
            v_trade_price := greatest(0.000001, p_avg_cost_nav_end * 0.5);
            v_rebalance_shares :=
                v_shares * (v_avg - p_avg_cost_nav_end)
                / greatest(p_avg_cost_nav_end - v_trade_price, 1e-9);
        end if;

        v_created_at := v_created_at + interval '1 microsecond';
        insert into public.app_adjustments (
            id, user_id, type, code, effective_date, shares, price,
            cash, note, source, created_at
        ) values (
            replace(gen_random_uuid()::text, '-', ''), p_user_id, 'BUY',
            p_code, p_effective_date, v_rebalance_shares, v_trade_price, 0,
            coalesce(v_note, 'edit->COST_REBALANCE_BUY'), 'ui_edit', v_created_at
        );
        v_old_amount := v_shares * v_avg;
        v_shares := v_shares + v_rebalance_shares;
        v_avg := (v_old_amount + v_rebalance_shares * v_trade_price) / v_shares;

        v_created_at := v_created_at + interval '1 microsecond';
        insert into public.app_adjustments (
            id, user_id, type, code, effective_date, shares, price,
            cash, note, source, created_at
        ) values (
            replace(gen_random_uuid()::text, '-', ''), p_user_id, 'SELL',
            p_code, p_effective_date, v_rebalance_shares, p_avg_cost_nav_end, 0,
            coalesce(v_note, 'edit->COST_REBALANCE_SELL'), 'ui_edit', v_created_at
        );
        v_realized :=
            v_realized + (p_avg_cost_nav_end - v_avg) * v_rebalance_shares;
        v_shares := v_shares - v_rebalance_shares;
        if v_shares <= 1e-9 then
            v_shares := 0;
            v_avg := 0;
        end if;
        v_inserted := v_inserted + 2;
    end if;

    v_delta := p_realized_pnl_end - v_realized;
    if abs(v_delta) > 1e-6 then
        v_created_at := v_created_at + interval '1 microsecond';
        insert into public.app_adjustments (
            id, user_id, type, code, effective_date, shares, price,
            cash, note, source, created_at
        ) values (
            replace(gen_random_uuid()::text, '-', ''), p_user_id, 'CASH_ADJ',
            p_code, p_effective_date, 0, 0, v_delta,
            coalesce(v_note, 'edit->CASH_ADJ'), 'ui_edit', v_created_at
        );
        v_inserted := v_inserted + 1;
    end if;

    return jsonb_build_object(
        'ok', true,
        'deleted', v_deleted,
        'inserted', v_inserted
    );
end
$$;

revoke all on function public.app_apply_position_edit(
    text, date, text, double precision, double precision, double precision, text
) from public, anon;
grant execute on function public.app_apply_position_edit(
    text, date, text, double precision, double precision, double precision, text
) to authenticated, service_role;

commit;
